baseURL = 'https://tonedesu.github.io/'
languageCode = 'en-us'
title = 'Learning Go/Hugo and making my website'
theme = 'ananke'
[caches]
[caches.images]
dir = ':cacheDir/images'
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
